goodreads_key = "your_actual_goodreads_api_key"
OPENAI_API_KEY = "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"
