goodreads_key = "your_actual_goodreads_api_key"
OPENAI_API_KEY = "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"

