goodreads_key = "your_actual_goodreads_api_key"
OPENAI_API_KEY = "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"

